name: inbreast-bi-rads
task: INBREAST
#data_dir: "/home/nvidia/datasets/inbreast-augmented/bi-rads-cls"
data_dir: "./data/CBIS_DDSM"
log_dir: "./logs"
seed: 1234

batch_size: 8
input_size: 64 #128
max_latency: 80

epochs: 5
lr: .0001